package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	cwd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}

	err = filepath.WalkDir(cwd, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if d.Name() == "vendor" || strings.HasPrefix(d.Name(), ".") {
				return filepath.SkipDir
			}
			processPackage(path)
		}
		return nil
	})

	if err != nil {
		log.Fatal(err)
	}
}

type structInfo struct {
	Name   string
	Fields []*ast.Field
}

func processPackage(path string) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, path, nil, parser.ParseComments)
	if err != nil {
		return
	}

	for _, pkg := range pkgs {
		var structs []structInfo
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				if !hasResetComment(genDecl) {
					continue
				}

				for _, spec := range genSpec(genDecl) {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					structs = append(structs, structInfo{
						Name:   typeSpec.Name.Name,
						Fields: structType.Fields.List,
					})
				}
			}
		}

		if len(structs) > 0 {
			generateFile(path, pkg.Name, structs)
		}
	}
}

func hasResetComment(decl *ast.GenDecl) bool {
	if decl.Doc == nil {
		return false
	}
	for _, comment := range decl.Doc.List {
		if strings.Contains(comment.Text, "// generate:reset") {
			return true
		}
	}
	return false
}

func genSpec(decl *ast.GenDecl) []ast.Spec {
	return decl.Specs
}

func generateFile(dir, pkgName string, structs []structInfo) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by reset generator; DO NOT EDIT.\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for _, s := range structs {
		fmt.Fprintf(&buf, "func (rs *%s) Reset() {\n", s.Name)
		fmt.Fprintf(&buf, "\tif rs == nil {\n\t\treturn\n\t}\n\n")

		for _, field := range s.Fields {
			for _, name := range field.Names {
				generateResetForField(&buf, name.Name, field.Type)
			}
		}
		fmt.Fprintf(&buf, "}\n\n")
	}

	outPath := filepath.Join(dir, "reset.gen.go")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("failed to format %s: %v", outPath, err)
		formatted = buf.Bytes()
	}

	err = os.WriteFile(outPath, formatted, 0644)
	if err != nil {
		log.Printf("failed to write %s: %v", outPath, err)
	} else {
		fmt.Printf("Generated %s\n", outPath)
	}
}

func generateResetForField(buf *bytes.Buffer, name string, expr ast.Expr) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte", "rune":
			fmt.Fprintf(buf, "\trs.%s = 0\n", name)
		case "float32", "float64":
			fmt.Fprintf(buf, "\trs.%s = 0.0\n", name)
		case "string":
			fmt.Fprintf(buf, "\trs.%s = \"\"\n", name)
		case "bool":
			fmt.Fprintf(buf, "\trs.%s = false\n", name)
		case "error":
			fmt.Fprintf(buf, "\trs.%s = nil\n", name)
		default:
			// Likely a custom type or struct in the same package
			fmt.Fprintf(buf, "\tif resetter, ok := interface{}(&rs.%s).(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t}\n", name)
		}
	case *ast.ArrayType:
		fmt.Fprintf(buf, "\trs.%s = rs.%s[:0]\n", name, name)
	case *ast.MapType:
		fmt.Fprintf(buf, "\tclear(rs.%s)\n", name)
	case *ast.StarExpr:
		fmt.Fprintf(buf, "\tif rs.%s != nil {\n", name)
		// Recursively reset pointed value
		generateResetForPointer(buf, name, t.X)
		fmt.Fprintf(buf, "\t}\n")
	case *ast.SelectorExpr:
		// External package type
		fmt.Fprintf(buf, "\tif resetter, ok := interface{}(&rs.%s).(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t}\n", name)
	case *ast.InterfaceType:
		fmt.Fprintf(buf, "\tif resetter, ok := rs.%s.(interface{ Reset() }); ok && rs.%s != nil {\n\t\tresetter.Reset()\n\t}\n", name, name)
	default:
		fmt.Fprintf(buf, "\t// type %T not handled for %s\n", t, name)
	}
}

func generateResetForPointer(buf *bytes.Buffer, name string, expr ast.Expr) {
	switch t := expr.(type) {
	case *ast.Ident:
		switch t.Name {
		case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64", "uintptr", "byte", "rune":
			fmt.Fprintf(buf, "\t\t*rs.%s = 0\n", name)
		case "float32", "float64":
			fmt.Fprintf(buf, "\t\t*rs.%s = 0.0\n", name)
		case "string":
			fmt.Fprintf(buf, "\t\t*rs.%s = \"\"\n", name)
		case "bool":
			fmt.Fprintf(buf, "\t\t*rs.%s = false\n", name)
		default:
			fmt.Fprintf(buf, "\t\tif resetter, ok := interface{}(rs.%s).(interface{ Reset() }); ok {\n\t\t\tresetter.Reset()\n\t\t}\n", name)
		}
	case *ast.SelectorExpr:
		fmt.Fprintf(buf, "\t\tif resetter, ok := interface{}(rs.%s).(interface{ Reset() }); ok {\n\t\t\tresetter.Reset()\n\t\t}\n", name)
	default:
		fmt.Fprintf(buf, "\t\t// pointer to %T not handled for %s\n", t, name)
	}
}
