// Code generated by reset generator; DO NOT EDIT.
package testreset

func (rs *ResetableStruct) Reset() {
	if rs == nil {
		return
	}

	rs.i = 0
	rs.str = ""
	if rs.strP != nil {
		*rs.strP = ""
	}
	rs.s = rs.s[:0]
	clear(rs.m)
	if rs.child != nil {
		if resetter, ok := interface{}(rs.child).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}
